# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumTest01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumTest01(self):
    self.driver.get("https://the-internet.herokuapp.com/")
    self.driver.set_window_size(1230, 980)
    self.driver.find_element(By.LINK_TEXT, "Dropdown").click()
    dropdown = self.driver.find_element(By.ID, "dropdown")
    dropdown.find_element(By.XPATH, "//option[. = 'Option 1']").click()
    element = self.driver.find_element(By.ID, "dropdown")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "dropdown")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "dropdown")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
